/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_howarth_analysis_Analysis */

#ifndef _Included_io_howarth_analysis_Analysis
#define _Included_io_howarth_analysis_Analysis
#ifdef __cplusplus
extern "C" {
#endif
#undef io_howarth_analysis_Analysis_BOARD_SIZE
#define io_howarth_analysis_Analysis_BOARD_SIZE 11L
/*
 * Class:     io_howarth_analysis_Analysis
 * Method:    kingCorner
 * Signature: ([CBB)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_howarth_analysis_Analysis_kingCorner
  (JNIEnv *, jclass, jcharArray, jbyte, jbyte);

#ifdef __cplusplus
}
#endif
#endif
